### ISSUE TITLE
Great project!

### ISSUE THREAD

**Issue by sfmskywalker** [bs-components/bs-components#2]
Thank you for this awesome project! It is exactly what I need for my [current project](https://github.com/elsa-workflows/elsa-designer) where I want to take advantage of some of Bootstrap 4's widgets such as Modal. As I started to investigate how one would go about implementing one's own script to replace Bootstrap's jQuery script (to play nice as you perfectly described on this project's readme), I stumbled upon this GitHub repo.

I did notice it's been a while since you last pushed an update, so I took the liberty of forking & cloning the project and submit a [PR](https://github.com/bs-components/bs-components/pull/1) that just updates the NPM packages.

I'm hoping you will accept the PR (with any requests for change if you have them) and publish an updated version to NPM.

Looking forward to hearing from you!

**Comment by bs-components** [comment]
looks great, thank you for the PR!
